### ISSUE TITLE
[Assignment] 토이 프로젝트를 통해서 테스트 코드 연습하기

### ISSUE THREAD

**Issue by HELLOHIDI** [HELLOHIDI/TestingLab#1]
## 🛠 Issue
- 토이 프로젝트를 통해서 테스트 코드 연습하기

## 📋 To-do
- [ ] 로그인, 회원가입 로직 Domain / Repository / Servicef로 나누기
- [ ] MockData 이용해서 테스트 코드 작성하기
- [ ] Stub, Fake, Spy 등 다양한 Test Double 사용해보기
